name: Add label
on:
  push:
    branches: [ main ]
  pull_request:
env:
  TZ: "Asia/Tokyo"
jobs:
  label:
    name: Add label
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@1.0.2
        if: ${{ contains(github.event.pull_request.body, 'issues') }}
        with:
          add-labels: "label1"
          ignore-if-labeled: true
      - uses: andymckay/labeler@1.0.2
        if: ${{ contains(github.event.pull_request.body, 'Jenova') }}
        with:
          add-labels: "label2"
          ignore-if-labeled: true
