name: CI
on:
  push:
    branches:
      - feature/*
      - master
    paths-ignore:
      - README.md
jobs:
  ci:
    name: run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '16.3.0'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint
      - run: yarn test:ci
      - run: yarn build
