name: CI
on:
  push:
    branches:
      - feature/*
      - master
    paths-ignore:
      - README.md
jobs:
  ci:
    name: run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '15.x'
      - uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - run: yarn lint
      - run: yarn test:ci
      - run: yarn build
