name: Publish StoryBook
on:
  push:
    branches: [main]
env:
  TZ: 'Asia/Tokyo'
jobs:
  test:
    name: Publish StoryBook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
      - run: npm install
      - run: npm run build-storybook -o ./.dist/storybook
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.dist/storybook
          allow_empty_commit: true
