name: Publish StoryBook
on:
  push:
    branches: [main]
env:
  TZ: 'Asia/Tokyo'
jobs:
  test:
    name: Publish StoryBook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: npm
      - run: npm install
      - run: npm run build-storybook
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          allow_empty_commit: true
