name: Test
on:
  push:
    branches: [main]
  pull_request:
env:
  TZ: 'Asia/Tokyo'
jobs:
  test:
    name: Run test:ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: npm
      - run: npm install
      - run: npm run test:ci
